name: noor_player
description: A customizable video player with thumbnail and caching support.
version: 1.0.1
homepage: https://github.com/oalinoor11/noor_video_player

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.7.0
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.1
  dio: ^5.3.2
  video_thumbnail: ^0.5.3
  shimmer: ^3.0.0

flutter:
  uses-material-design: true